
#import "CityManager.h"

@implementation CityManager

+ (instancetype)sharedInstance {
    static CityManager *instance;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        instance = [[self alloc] init];
        [instance loadCityData];
    });
    return instance;
}

- (void)loadCityData {
    self.cityCodeMap = 
@{
    @"110101001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"东华门街道"},
@"110101002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"景山街道"},
@"110101003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"交道口街道"},
@"110101004": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"安定门街道"},
@"110101005": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"北新桥街道"},
@"110101006": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"东四街道"},
@"110101007": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"朝阳门街道"},
@"110101008": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"建国门街道"},
@"110101009": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"东直门街道"},
@"110101010": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"和平里街道"},
@"110101011": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"前门街道"},
@"110101012": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"崇文门外街道"},
@"110101013": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"东花市街道"},
@"110101014": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"龙潭街道"},
@"110101015": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"体育馆路街道"},
@"110101016": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"天坛街道"},
@"110101017": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"东城区", @"street": @"永定门外街道"},
@"110102001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"西长安街街道"},
@"110102003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"新街口街道"},
@"110102007": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"月坛街道"},
@"110102009": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"展览路街道"},
@"110102010": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"德胜街道"},
@"110102011": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"金融街街道"},
@"110102012": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"什刹海街道"},
@"110102013": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"大栅栏街道"},
@"110102014": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"天桥街道"},
@"110102015": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"椿树街道"},
@"110102016": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"陶然亭街道"},
@"110102017": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"广安门内街道"},
@"110102018": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"牛街街道"},
@"110102019": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"白纸坊街道"},
@"110102020": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"西城区", @"street": @"广安门外街道"},
@"110105001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"建外街道"},
@"110105002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"朝外街道"},
@"110105003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"呼家楼街道"},
@"110105004": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"三里屯街道"},
@"110105005": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"左家庄街道"},
@"110105006": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"香河园街道"},
@"110105007": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"和平街街道"},
@"110105008": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"安贞街道"},
@"110105009": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"亚运村街道"},
@"110105010": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"小关街道"},
@"110105011": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"酒仙桥街道"},
@"110105012": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"麦子店街道"},
@"110105013": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"团结湖街道"},
@"110105014": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"六里屯街道"},
@"110105015": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"八里庄街道"},
@"110105016": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"双井街道"},
@"110105017": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"劲松街道"},
@"110105018": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"潘家园街道"},
@"110105019": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"垡头街道"},
@"110105020": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"首都机场街道"},
@"110105021": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"南磨房地区"},
@"110105022": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"高碑店地区"},
@"110105023": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"将台地区"},
@"110105024": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"太阳宫地区"},
@"110105025": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"大屯街道"},
@"110105026": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"望京街道"},
@"110105027": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"小红门地区"},
@"110105028": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"十八里店地区"},
@"110105029": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"平房地区"},
@"110105030": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"东风地区"},
@"110105031": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"奥运村街道"},
@"110105032": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"来广营地区"},
@"110105033": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"常营地区"},
@"110105034": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"三间房地区"},
@"110105035": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"管庄地区"},
@"110105036": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"金盏地区"},
@"110105037": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"孙河地区"},
@"110105038": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"崔各庄地区"},
@"110105039": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"东坝地区"},
@"110105040": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"黑庄户地区"},
@"110105041": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"豆各庄地区"},
@"110105042": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"王四营地区"},
@"110105043": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"朝阳区", @"street": @"东湖街道"},
@"110106001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"右安门街道"},
@"110106002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"太平桥街道"},
@"110106003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"西罗园街道"},
@"110106004": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"大红门街道"},
@"110106005": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"南苑街道"},
@"110106006": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"东高地街道"},
@"110106007": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"东铁匠营街道"},
@"110106008": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"六里桥街道"},
@"110106009": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"丰台街道"},
@"110106010": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"新村街道"},
@"110106011": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"长辛店街道"},
@"110106012": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"云岗街道"},
@"110106013": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"方庄街道"},
@"110106014": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"宛平街道"},
@"110106015": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"马家堡街道"},
@"110106016": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"和义街道"},
@"110106017": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"卢沟桥街道"},
@"110106018": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"花乡街道"},
@"110106020": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"成寿寺街道"},
@"110106021": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"石榴庄街道"},
@"110106022": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"玉泉营街道"},
@"110106023": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"看丹街道"},
@"110106024": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"五里店街道"},
@"110106025": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"青塔街道"},
@"110106100": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"北宫镇"},
@"110106101": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"丰台区", @"street": @"王佐镇"},
@"110107001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"石景山区", @"street": @"八宝山街道"},
@"110107002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"石景山区", @"street": @"老山街道"},
@"110107003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"石景山区", @"street": @"八角街道"},
@"110107004": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"石景山区", @"street": @"古城街道"},
@"110107005": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"石景山区", @"street": @"苹果园街道"},
@"110107006": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"石景山区", @"street": @"金顶街街道"},
@"110107009": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"石景山区", @"street": @"广宁街道"},
@"110107010": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"石景山区", @"street": @"五里坨街道"},
@"110107011": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"石景山区", @"street": @"鲁谷街道"},
@"110108001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"万寿路街道"},
@"110108002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"永定路街道"},
@"110108003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"羊坊店街道"},
@"110108004": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"甘家口街道"},
@"110108005": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"八里庄街道"},
@"110108006": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"紫竹院街道"},
@"110108007": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"北下关街道"},
@"110108008": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"北太平庄街道"},
@"110108010": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"学院路街道"},
@"110108011": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"中关村街道"},
@"110108012": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"海淀街道"},
@"110108013": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"青龙桥街道"},
@"110108014": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"清华园街道"},
@"110108015": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"燕园街道"},
@"110108016": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"香山街道"},
@"110108017": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"清河街道"},
@"110108018": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"花园路街道"},
@"110108019": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"西三旗街道"},
@"110108020": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"马连洼街道"},
@"110108021": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"田村路街道"},
@"110108022": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"上地街道"},
@"110108023": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"万柳地区"},
@"110108024": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"东升地区"},
@"110108025": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"曙光街道"},
@"110108026": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"温泉地区"},
@"110108027": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"四季青地区"},
@"110108028": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"西北旺地区"},
@"110108029": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"苏家坨地区"},
@"110108030": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"海淀区", @"street": @"上庄地区"},
@"110109001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"门头沟区", @"street": @"大峪街道"},
@"110109002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"门头沟区", @"street": @"城子街道"},
@"110109003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"门头沟区", @"street": @"东辛房街道"},
@"110109004": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"门头沟区", @"street": @"大台街道"},
@"110109005": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"门头沟区", @"street": @"王平地区"},
@"110109006": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"门头沟区", @"street": @"永定地区"},
@"110109007": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"门头沟区", @"street": @"龙泉地区"},
@"110109101": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"门头沟区", @"street": @"潭柘寺镇"},
@"110109104": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"门头沟区", @"street": @"军庄镇"},
@"110109105": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"门头沟区", @"street": @"雁翅镇"},
@"110109106": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"门头沟区", @"street": @"斋堂镇"},
@"110109107": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"门头沟区", @"street": @"清水镇"},
@"110109108": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"门头沟区", @"street": @"妙峰山镇"},
@"110111001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"城关街道"},
@"110111002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"新镇街道"},
@"110111004": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"向阳街道"},
@"110111005": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"东风街道"},
@"110111006": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"迎风街道"},
@"110111007": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"星城街道"},
@"110111008": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"良乡地区"},
@"110111009": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"周口店地区"},
@"110111010": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"琉璃河地区"},
@"110111011": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"拱辰街道"},
@"110111012": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"西潞街道"},
@"110111101": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"阎村镇"},
@"110111103": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"窦店镇"},
@"110111104": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"石楼镇"},
@"110111105": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"长阳镇"},
@"110111107": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"河北镇"},
@"110111108": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"长沟镇"},
@"110111109": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"大石窝镇"},
@"110111110": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"张坊镇"},
@"110111111": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"十渡镇"},
@"110111112": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"青龙湖镇"},
@"110111115": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"韩村河镇"},
@"110111208": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"霞云岭乡"},
@"110111209": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"南窖乡"},
@"110111210": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"佛子庄乡"},
@"110111211": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"大安山乡"},
@"110111212": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"史家营乡"},
@"110111213": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"房山区", @"street": @"蒲洼乡"},
@"110112001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"中仓街道"},
@"110112002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"新华街道"},
@"110112003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"北苑街道"},
@"110112004": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"玉桥街道"},
@"110112007": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"潞源街道"},
@"110112008": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"通运街道"},
@"110112009": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"文景街道"},
@"110112010": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"九棵树街道"},
@"110112011": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"临河里街道"},
@"110112012": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"杨庄街道"},
@"110112013": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"潞邑街道"},
@"110112104": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"宋庄镇"},
@"110112105": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"张家湾镇"},
@"110112106": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"漷县镇"},
@"110112109": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"马驹桥镇"},
@"110112110": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"西集镇"},
@"110112114": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"台湖镇"},
@"110112117": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"永乐店镇"},
@"110112119": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"潞城镇"},
@"110112120": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"永顺镇"},
@"110112121": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"梨园镇"},
@"110112209": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"通州区", @"street": @"于家务回族乡"},
@"110113001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"胜利街道"},
@"110113002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"光明街道"},
@"110113003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"仁和地区"},
@"110113004": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"后沙峪地区"},
@"110113005": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"天竺地区"},
@"110113006": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"杨镇地区"},
@"110113007": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"牛栏山地区"},
@"110113008": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"南法信地区"},
@"110113009": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"马坡地区"},
@"110113010": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"石园街道"},
@"110113011": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"空港街道"},
@"110113012": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"双丰街道"},
@"110113013": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"旺泉街道"},
@"110113101": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"高丽营镇"},
@"110113104": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"李桥镇"},
@"110113105": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"李遂镇"},
@"110113106": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"南彩镇"},
@"110113108": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"北务镇"},
@"110113109": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"大孙各庄镇"},
@"110113110": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"张镇"},
@"110113111": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"龙湾屯镇"},
@"110113112": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"木林镇"},
@"110113113": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"北小营镇"},
@"110113115": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"北石槽镇"},
@"110113116": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"顺义区", @"street": @"赵全营镇"},
@"110114001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"城北街道"},
@"110114002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"南口地区"},
@"110114003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"马池口地区"},
@"110114004": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"沙河地区"},
@"110114005": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"城南街道"},
@"110114007": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"东小口地区"},
@"110114008": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"天通苑北街道"},
@"110114009": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"天通苑南街道"},
@"110114010": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"霍营街道"},
@"110114011": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"回龙观街道"},
@"110114012": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"龙泽园街道"},
@"110114013": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"史各庄街道"},
@"110114104": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"阳坊镇"},
@"110114110": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"小汤山镇"},
@"110114111": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"南邵镇"},
@"110114112": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"崔村镇"},
@"110114113": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"百善镇"},
@"110114115": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"北七家镇"},
@"110114116": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"兴寿镇"},
@"110114118": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"流村镇"},
@"110114119": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"十三陵镇"},
@"110114120": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"昌平区", @"street": @"延寿镇"},
@"110115001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"兴丰街道"},
@"110115002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"林校路街道"},
@"110115003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"清源街道"},
@"110115004": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"亦庄地区"},
@"110115005": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"黄村地区"},
@"110115006": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"旧宫地区"},
@"110115007": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"西红门地区"},
@"110115008": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"瀛海地区"},
@"110115009": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"观音寺街道"},
@"110115010": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"天宫院街道"},
@"110115011": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"高米店街道"},
@"110115012": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"荣华街道"},
@"110115013": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"博兴街道"},
@"110115103": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"青云店镇"},
@"110115104": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"采育镇"},
@"110115105": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"安定镇"},
@"110115106": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"礼贤镇"},
@"110115107": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"榆垡镇"},
@"110115108": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"庞各庄镇"},
@"110115109": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"北臧村镇"},
@"110115110": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"魏善庄镇"},
@"110115111": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"长子营镇"},
@"110115403": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"北京经济技术开发区"},
@"110115404": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"中关村国家自主创新示范区大兴生物医药产业基地"},
@"110115405": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"大兴经济开发区"},
@"110115406": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"大兴区", @"street": @"大兴国际机场"},
@"110116001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"泉河街道"},
@"110116002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"龙山街道"},
@"110116003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"怀柔地区"},
@"110116004": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"雁栖地区"},
@"110116005": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"庙城地区"},
@"110116102": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"北房镇"},
@"110116103": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"杨宋镇"},
@"110116105": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"桥梓镇"},
@"110116106": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"怀北镇"},
@"110116107": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"汤河口镇"},
@"110116108": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"渤海镇"},
@"110116109": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"九渡河镇"},
@"110116110": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"琉璃庙镇"},
@"110116111": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"宝山镇"},
@"110116211": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"长哨营满族乡"},
@"110116213": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"喇叭沟门满族乡"},
@"110116400": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"怀柔区", @"street": @"北京雁栖经济开发区"},
@"110117001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"滨河街道"},
@"110117002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"兴谷街道"},
@"110117003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"渔阳地区"},
@"110117004": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"峪口地区"},
@"110117005": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"马坊地区"},
@"110117006": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"金海湖地区"},
@"110117101": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"东高村镇"},
@"110117102": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"山东庄镇"},
@"110117104": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"南独乐河镇"},
@"110117105": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"大华山镇"},
@"110117106": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"夏各庄镇"},
@"110117108": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"马昌营镇"},
@"110117110": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"王辛庄镇"},
@"110117111": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"大兴庄镇"},
@"110117112": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"刘家店镇"},
@"110117114": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"镇罗营镇"},
@"110117213": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"黄松峪乡"},
@"110117214": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"平谷区", @"street": @"熊儿寨乡"},
@"110118001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"鼓楼街道"},
@"110118002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"果园街道"},
@"110118003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"檀营地区"},
@"110118100": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"密云镇"},
@"110118101": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"溪翁庄镇"},
@"110118102": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"西田各庄镇"},
@"110118103": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"十里堡镇"},
@"110118104": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"河南寨镇"},
@"110118105": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"巨各庄镇"},
@"110118106": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"穆家峪镇"},
@"110118107": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"太师屯镇"},
@"110118108": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"高岭镇"},
@"110118109": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"不老屯镇"},
@"110118110": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"冯家峪镇"},
@"110118111": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"古北口镇"},
@"110118112": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"大城子镇"},
@"110118113": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"东邵渠镇"},
@"110118114": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"北庄镇"},
@"110118115": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"新城子镇"},
@"110118116": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"石城镇"},
@"110118400": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"密云区", @"street": @"中关村科技园区密云园"},
@"110119001": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"百泉街道"},
@"110119002": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"香水园街道"},
@"110119003": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"儒林街道"},
@"110119100": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"延庆镇"},
@"110119101": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"康庄镇"},
@"110119102": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"八达岭镇"},
@"110119103": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"永宁镇"},
@"110119104": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"旧县镇"},
@"110119105": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"张山营镇"},
@"110119106": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"四海镇"},
@"110119107": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"千家店镇"},
@"110119108": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"沈家营镇"},
@"110119109": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"大榆树镇"},
@"110119110": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"井庄镇"},
@"110119200": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"大庄科乡"},
@"110119201": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"刘斌堡乡"},
@"110119202": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"香营乡"},
@"110119203": @{@"province": @"北京市", @"city": @"市辖区", @"district": @"延庆区", @"street": @"珍珠泉乡"}
};
}

- (NSString *)getProvinceNameWithCode:(NSString *)code {
    return self.cityCodeMap[code][@"province"] ?: @"";
}

- (NSString *)getCityNameWithCode:(NSString *)code {
    return self.cityCodeMap[code][@"city"] ?: @"";
}

- (NSString *)getDistrictNameWithCode:(NSString *)code {
    return self.cityCodeMap[code][@"district"] ?: @"";
}

- (NSString *)getStreetNameWithCode:(NSString *)code {
    return self.cityCodeMap[code][@"street"] ?: @"";
}

@end
